version: '3.1'

services:
  powerbiz_writedb:
    image: postgres:11
    container_name: powerbiz_writedb
    hostname: powerbiz_writedb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Default123
      - POSTGRES_DB=powerbiz_writedb
      - POSTGRES_HOSTNAME=powerbiz_writedb
    ports:
      - 5431:5432
    volumes:
      - powerbiz_writedata:/var/lib/postgresql/data
    networks:
      - powerbizNet

  powerbiz_readdb:
    image: postgres:11
    container_name: powerbiz_readdb
    hostname: powerbiz_readdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Default123
      - POSTGRES_DB=powerbiz
      - POSTGRES_HOSTNAME=powerbiz_readdb
    ports:
      - 5432:5432
    volumes:
      - powerbiz_readdata:/var/lib/postgresql/data
    networks:
      - powerbizNet

  axonserver:
    image: axoniq/axonserver
    container_name: powerbiz_axon
    hostname: axonserver
    environment:
      - AXONSERVER_HOSTNAME=axonserver
    ports:
      - 8024:8024
    networks:
      - powerbizNet

  rabbitmq:
    image: rabbitmq:3
    container_name: powerbiz_rabbitmq
    environment:
      - RABBITMQ_HOSTNAME=powerbiz_rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - powerbizNet

  usercmdsvc:
    build:
      context: .
      dockerfile: ./usercmdsvc/Dockerfile
    container_name: user-command-svc
    environment:
      - AXONSERVER_HOST=axonserver
    ports:
      - 8081:8081
    depends_on:
      - axonserver
    networks:
      - powerbizNet

  userquerysvc:
    build:
      context: .
      dockerfile: ./userquerysvc/Dockerfile
    container_name: user-query-svc
    environment:
      - AXONSERVER_HOST=axonserver
      - POSTGRES_HOSTNAME=powerbiz_readdb
    ports:
      - 8082:8082
    depends_on:
      - axonserver
      - powerbiz_readdb
    networks:
      - powerbizNet

volumes:
  powerbiz_writedata:
  powerbiz_readdata:

networks:
  powerbizNet:
    driver: bridge
