version: '3.1'

services:
  powerbizwdb:
    image: postgres:11
    container_name: powerbizwdb
    hostname: powerbizwdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Default123
      - POSTGRES_DB=powerbiz_writedb
      - POSTGRES_HOST=powerbizwdb
    volumes:
      - powerbizwdb:/var/lib/postgresql/data
    networks:
      - powerbizNet

  powerbizrdb:
    image: postgres:11
    container_name: powerbizrdb
    hostname: powerbizrdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Default123
      - POSTGRES_DB=powerbiz_readdb
      - POSTGRES_HOST=powerbizrdb
    volumes:
      - powerbizrdb:/var/lib/postgresql/data
    networks:
      - powerbizNet

  rabbitmq:
    image: rabbitmq:3
    container_name: powerbiz_rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - powerbizNet

  usercmdsvc:
    build:
      context: .
      dockerfile: ./usercmdsvc/Dockerfile
    container_name: user-command-svc
    environment:
      - POSTGRES_HOST=powerbizwdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Default123
      - POSTGRES_PORT=5432
      - POSTGRES_DB=powerbiz_writedb
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - 8081:8081
    depends_on:
      - powerbizwdb
      - rabbitmq
    networks:
      - powerbizNet

  userquerysvc:
    build:
      context: .
      dockerfile: ./userquerysvc/Dockerfile
    container_name: user-query-svc
    environment:
      - POSTGRES_HOST=powerbizrdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Default123
      - POSTGRES_DB=powerbiz_readdb
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - 8082:8082
    depends_on:
      - powerbizrdb
      - rabbitmq
    networks:
      - powerbizNet

volumes:
  powerbizwdb:
  powerbizrdb:

networks:
  powerbizNet:
    driver: bridge
