version: '3.1'

services:
  powerbiz_writedb:
    image: postgres:11
    container_name: powerbiz_writedb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Default123
      - POSTGRES_DB=powerbiz_writedb
    ports:
      - 5431:5432
    volumes:
      - powerbiz_writedata:/var/lib/postgresql/data
    networks:
      - powerbizNet

  powerbiz_readdb:
    image: postgres:11
    container_name: powerbiz_readdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Default123
      - POSTGRES_DB=powerbiz_readdb
    ports:
      - 5432:5432
    volumes:
      - powerbiz_readdata:/var/lib/postgresql/data
    networks:
      - powerbizNet

  rabbitmq:
    image: rabbitmq:3
    container_name: powerbiz_rabbitmq
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15691:15691
      - 15692:15692
      - 25672:25672
      - 15671:15671
      - 15672:15672
    networks:
      - powerbizNet

  opa_engine:
    image: openpolicyagent/opa:edge-rootless
    container_name: opa_engine
    ports:
      - 8181:8181
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
    networks:
      - powerbizNet

volumes:
  powerbiz_writedata:
  powerbiz_readdata:

networks:
  powerbizNet:
    driver: bridge
