server:
  port: 8081
  error:
    include-message: always

logging:
  level:
    root: INFO

spring:
  application:
    name: "user-command"
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: "postgres"
    url: "jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5431}/powerbiz_writedb"
    username: postgres
    password: Default123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    generate-ddl: true
  rabbitmq:
    host: "${RABBITMQ_HOSTNAME:localhost}"
    port: 5672
    virtual-host: /
    username: "${RABBITMQ_USERNAME:guest}"
    password: "${RABBITMQ_PASSWORD:guest}"
  cloud:
    stream:
      producer:
        produce: false
      default-binder: rabbit
      default:
        content-type: application/json
      bindings:
        userRegistered-out-0:
          destination: userEvents.topic
          group: userEvents
          producer:
            required-groups: userEvents
      rabbit:
        bindings:
          userRegistered-out-0:
            producer:
              queue-name-group-only: true
              binding-routing-key: userRegisteredEvent
              routing-key-expression: '''userRegisteredEvent'''

axon:
  serializer:
    general: xstream
    messages: jackson
    events: jackson
