server:
  port: 8082

spring:
  application:
    name: "user-query"
  rabbitmq:
    host: "${RABBITMQ_HOSTNAME:localhost}"
    port: 5672
    username: "${RABBITMQ_USERNAME:guest}"
    password: "${RABBITMQ_PASSWORD:guest}"
    virtual-host: /
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: "postgres"
    url: "jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/user_readdb"
    username: postgres
    password: Default123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    generate-ddl: true

axon:
  amqp:
    exchange: userEvents.topic
  eventhandling:
    processors:
      userEvents:
        source: rabbitMQSpringAMQPMessageSource
        mode: subscribing
  serializer:
    general: xstream
    messages: jackson
    events: jackson
