server:
  port: 8082

spring:
  application:
    name: "user-query"
  rabbitmq:
    host: "${RABBITMQ_HOSTNAME:localhost}"
    port: 5672
    username: "${RABBITMQ_USERNAME:guest}"
    password: "${RABBITMQ_PASSWORD:guest}"
    virtual-host: /
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: "postgres"
    url: "jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/powerbiz_readdb"
    username: postgres
    password: Default123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    generate-ddl: true
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: 5a57e210-1e8c-41b6-a6a8-64b23a5d17ca
            client-secret: e2ID__PrNWjm7FY3a_F8Fu6s~ihVsv~3.V

axon:
  amqp:
    exchange: userEvents.topic
  eventhandling:
    processors:
      userEvents:
        source: rabbitMQSpringAMQPMessageSource
        mode: subscribing
  serializer:
    general: xstream
    messages: jackson
    events: jackson

azure:
  activedirectory:
    tenant-id: 6a92eb64-8e1b-44eb-b240-3f4485c188b6